#!/usr/bin/python3
# -*- coding: utf-8 -*-
# TextDemo 
# generated by Structorizer 3.32-36 

# Copyright (C) 2019-10-10 Kay Gürtzig 
# License: GPLv3-link 
# GNU General Public License (V 3) 
# https://www.gnu.org/licenses/gpl.html 
# http://www.gnu.de/documents/gpl.de.html 

from enum import Enum
import math

def backward(len, color) :
    if ((color) == 1) :
        # col29f69090 = turtle.pencolor(); turtle.pencolor("#000000")
        backward(len)
        # turtle.pencolor(col29f69090)
    elif ((color) == 2) :
        # col568bf312 = turtle.pencolor(); turtle.pencolor("#ff8080")
        backward(len)
        # turtle.pencolor(col568bf312)
    elif ((color) == 3) :
        # colca263c2 = turtle.pencolor(); turtle.pencolor("#ffff80")
        backward(len)
        # turtle.pencolor(colca263c2)
    elif ((color) == 4) :
        # col589b3632 = turtle.pencolor(); turtle.pencolor("#80ff80")
        backward(len)
        # turtle.pencolor(col589b3632)
    elif ((color) == 5) :
        # col45f45fa1 = turtle.pencolor(); turtle.pencolor("#80ffff")
        backward(len)
        # turtle.pencolor(col45f45fa1)
    elif ((color) == 6) :
        # col4c6e276e = turtle.pencolor(); turtle.pencolor("#0080ff")
        backward(len)
        # turtle.pencolor(col4c6e276e)
    elif ((color) == 7) :
        # col534df152 = turtle.pencolor(); turtle.pencolor("#ff80c0")
        backward(len)
        # turtle.pencolor(col534df152)
    elif ((color) == 8) :
        # col52e677af = turtle.pencolor(); turtle.pencolor("#c0c0c0")
        backward(len)
        # turtle.pencolor(col52e677af)
    elif ((color) == 9) :
        # col35083305 = turtle.pencolor(); turtle.pencolor("#ff8000")
        backward(len)
        # turtle.pencolor(col35083305)
    elif ((color) == 10) :
        # col8e0379d = turtle.pencolor(); turtle.pencolor("#8080ff")
        backward(len)
        # turtle.pencolor(col8e0379d)

# Draws a blank for font height h, ignoring the colorNo 
def blank(h, colorNo) :
    width <- h/2.0
    penUp()
    right(90)
    # col2145433b = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width)
    left(90)
    # turtle.pencolor(col2145433b)

def forward(len, color) :
    if ((color) == 1) :
        # col2890c451 = turtle.pencolor(); turtle.pencolor("#000000")
        forward(len)
        # turtle.pencolor(col2890c451)
    elif ((color) == 2) :
        # col40e6dfe1 = turtle.pencolor(); turtle.pencolor("#ff8080")
        forward(len)
        # turtle.pencolor(col40e6dfe1)
    elif ((color) == 3) :
        # col1b083826 = turtle.pencolor(); turtle.pencolor("#ffff80")
        forward(len)
        # turtle.pencolor(col1b083826)
    elif ((color) == 4) :
        # col105fece7 = turtle.pencolor(); turtle.pencolor("#80ff80")
        forward(len)
        # turtle.pencolor(col105fece7)
    elif ((color) == 5) :
        # col3ec300f1 = turtle.pencolor(); turtle.pencolor("#80ffff")
        forward(len)
        # turtle.pencolor(col3ec300f1)
    elif ((color) == 6) :
        # col482cd91f = turtle.pencolor(); turtle.pencolor("#0080ff")
        forward(len)
        # turtle.pencolor(col482cd91f)
    elif ((color) == 7) :
        # col123f1134 = turtle.pencolor(); turtle.pencolor("#ff80c0")
        forward(len)
        # turtle.pencolor(col123f1134)
    elif ((color) == 8) :
        # col7d68ef40 = turtle.pencolor(); turtle.pencolor("#c0c0c0")
        forward(len)
        # turtle.pencolor(col7d68ef40)
    elif ((color) == 9) :
        # col5b0abc94 = turtle.pencolor(); turtle.pencolor("#ff8000")
        forward(len)
        # turtle.pencolor(col5b0abc94)
    elif ((color) == 10) :
        # col75c072cb = turtle.pencolor(); turtle.pencolor("#8080ff")
        forward(len)
        # turtle.pencolor(col75c072cb)

# Draws digit 1 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit1(h, colorNo) :
    penUp()
    # col1f1c7bf6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    penDown()
    # turtle.pencolor(col1f1c7bf6)
    right(45)
    forward(h/math.sqrt(2), colorNo)
    left(45)
    backward(h, colorNo)

# Draws digit 4 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit4(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    # inner angle at top of the triangle 
    angle <- math.degrees(math.atan(1 - 2.0*c/h))
    right(90)
    penUp()
    # col3c87521 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c + b)
    penDown()
    # turtle.pencolor(col3c87521)
    left(90)
    forward(h, colorNo)
    left(180 - angle)
    forward(math.sqrt(h*h/4.0 + sqr(h/2.0 - c)), colorNo)
    left(90 + angle)
    forward(h/2.0, colorNo)
    penUp()
    left(90)
    # col2aece37d = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h/2.0)
    penDown()
    # turtle.pencolor(col2aece37d)

# Draws digit 7 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit7(h, colorNo) :
    angle <- 90 + math.degrees(math.atan(0.5))
    penUp()
    # col5762806e = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    penDown()
    # turtle.pencolor(col5762806e)
    right(90)
    forward(h/2.0, colorNo)
    right(angle)
    forward(h * math.sqrt(1.25), colorNo)
    left(angle)
    penUp()
    # col17c386de = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col17c386de)

# Draws letter A in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterA(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(h*h + width*width/4.0)
    rotAngle <- math.degrees(math.atan(width/2.0/h))
    right(rotAngle)
    forward(hypo/2.0, colorNo)
    right(90 - rotAngle)
    forward(width/2.0, colorNo)
    penUp()
    # col16aa0a0a = turtle.pencolor(); turtle.pencolor("#000000")
    backward(width/2.0)
    penDown()
    # turtle.pencolor(col16aa0a0a)
    left(90 - rotAngle)
    forward(hypo/2.0, colorNo)
    left(2*rotAngle)
    forward(-hypo, colorNo)
    right(rotAngle)

# Draws letter E in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterE(h, colorNo) :
    width <- h/2.0
    forward(h, colorNo)
    right(90)
    forward(width, colorNo)
    right(90)
    penUp()
    # col691a7f8f = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    right(90)
    penDown()
    # turtle.pencolor(col691a7f8f)
    forward(width, colorNo)
    left(90)
    penUp()
    # col50a7bc6e = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col50a7bc6e)
    forward(width, colorNo)
    left(90)

# Draws letter F in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterF(h, colorNo) :
    width <- h/2.0
    forward(h, colorNo)
    right(90)
    forward(width, colorNo)
    right(90)
    penUp()
    # col17c1bced = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    right(90)
    penDown()
    # turtle.pencolor(col17c1bced)
    forward(width, colorNo)
    left(90)
    penUp()
    # col2d9d4f9d = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    left(90)
    forward(width)
    penDown()
    # turtle.pencolor(col2d9d4f9d)
    left(90)

# Draws letter H in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterH(h, colorNo) :
    width <- h/2.0
    forward(h, colorNo)
    penUp()
    right(90)
    # cole50a6f6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width)
    right(90)
    penDown()
    # turtle.pencolor(cole50a6f6)
    forward(h/2.0, colorNo)
    right(90)
    forward(width, colorNo)
    penUp()
    # col14ec4505 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(width)
    left(90)
    penDown()
    # turtle.pencolor(col14ec4505)
    forward(h/2.0, colorNo)
    left(180)

# Draws letter I in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterI(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    right(90)
    # col3ee0fea4 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col3ee0fea4)
    forward(b, colorNo)
    penUp()
    # col48524010 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(b/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col48524010)
    forward(h, colorNo)
    penUp()
    right(90)
    # col4b168fa9 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(b/2.0)
    penDown()
    # turtle.pencolor(col4b168fa9)
    forward(b, colorNo)
    penUp()
    # col1a84f40f = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b/2 + c)
    left(90)
    backward(h)
    penDown()
    # turtle.pencolor(col1a84f40f)

# Draws letter K in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterK(h, colorNo) :
    width <- h/2.0
    diag <- h/math.sqrt(2.0)
    forward(h, colorNo)
    penUp()
    right(90)
    # col6b419da = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width)
    right(135)
    penDown()
    # turtle.pencolor(col6b419da)
    forward(diag, colorNo)
    left(90)
    forward(diag, colorNo)
    left(135)

# Draws letter L in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterL(h, colorNo) :
    width <- h/2.0
    forward(h, colorNo)
    penUp()
    # col5906ebcb = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    right(90)
    penDown()
    # turtle.pencolor(col5906ebcb)
    forward(width, colorNo)
    left(90)

# Draws letter M in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterM(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(width*width + h*h)/2.0
    rotAngle <- math.degrees(math.atan(width/h))
    forward(h, colorNo)
    left(rotAngle)
    forward(-hypo, colorNo)
    right(2*rotAngle)
    forward(hypo, colorNo)
    left(rotAngle)
    forward(-h, colorNo)

# Draws letter N in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterN(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(width*width + h*h)
    rotAngle <- math.degrees(math.atan(width/h))
    forward(h, colorNo)
    left(rotAngle)
    forward(-hypo, colorNo)
    right(rotAngle)
    forward(h, colorNo)
    penUp()
    # col6646153 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col6646153)

# Draws letter T in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterT(h, colorNo) :
    width <- h/2.0
    penUp()
    # col143640d5 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    penDown()
    # turtle.pencolor(col143640d5)
    right(90)
    forward(width, colorNo)
    penUp()
    # col6295d394 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(width/2.0)
    penDown()
    # turtle.pencolor(col6295d394)
    right(90)
    forward(h, colorNo)
    left(90)
    penUp()
    # col475e586c = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width/2.0)
    penDown()
    # turtle.pencolor(col475e586c)
    left(90)

# Draws letter V in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterV(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(h*h + width*width/4.0)
    rotAngle <- math.degrees(math.atan(width/2.0/h))
    penUp()
    # col3a079870 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    left(rotAngle)
    penDown()
    # turtle.pencolor(col3a079870)
    forward(-hypo, colorNo)
    right(2*rotAngle)
    forward(hypo, colorNo)
    penUp()
    left(rotAngle)
    # col3b2cf7ab = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col3b2cf7ab)

# Draws letter W in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterW(h, colorNo) :
    width <- h/2.0
    width_3 <- width/3.0
    hypo <- math.sqrt(width_3*width_3 + h*h)
    rotAngle <- math.degrees(math.atan(width_3/h))
    penUp()
    # col3c153a1 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    left(rotAngle)
    penDown()
    # turtle.pencolor(col3c153a1)
    forward(-hypo, colorNo)
    right(2*rotAngle)
    forward(hypo, colorNo)
    penUp()
    left(90+rotAngle)
    # colb62fe6d = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width_3)
    right(90-rotAngle)
    penDown()
    # turtle.pencolor(colb62fe6d)
    forward(-hypo, colorNo)
    right(2*rotAngle)
    forward(hypo, colorNo)
    penUp()
    left(rotAngle)
    # col13acb0d1 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col13acb0d1)

# Draws letter X in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterX(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(width*width + h*h)
    rotAngle <- math.degrees(math.atan(width/h))
    right(rotAngle)
    forward(hypo, colorNo)
    penUp()
    left(90+rotAngle)
    # col5db45159 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(width)
    right(90-rotAngle)
    penDown()
    # turtle.pencolor(col5db45159)
    forward(-hypo, colorNo)
    right(rotAngle)

# Draws letter Y in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterY(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(width*width + h*h)/2.0
    rotAngle <- math.degrees(math.atan(width/h))
    penUp()
    # col6ab7a896 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    left(rotAngle)
    penDown()
    # turtle.pencolor(col6ab7a896)
    forward(-hypo, colorNo)
    right(rotAngle)
    penUp()
    # col327b636c = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h/2.0)
    penDown()
    # turtle.pencolor(col327b636c)
    forward(h/2.0, colorNo)
    right(rotAngle)
    forward(hypo, colorNo)
    left(rotAngle)
    penUp()
    # col45dd4eda = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col45dd4eda)

# Draws letter Z in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterZ(h, colorNo) :
    width <- h/2.0
    hypo <- math.sqrt(width*width + h*h)
    rotAngle <- math.degrees(math.atan(width/h))
    penUp()
    # col71c8becc = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    right(90)
    penDown()
    # turtle.pencolor(col71c8becc)
    forward(width, colorNo)
    left(90-rotAngle)
    forward(-hypo, colorNo)
    right(90-rotAngle)
    forward(width, colorNo)
    left(90)

# Draws nEdges edges of a regular n-polygon with edge length a 
# counter-clockwise, if ctrclkws is true, or clockwise if ctrclkws is false. 
def polygonPart(a, n, ctrclkws, nEdges, color) :
    rotAngle <- 360.0/n
    if (ctrclkws):
        rotAngle <- -rotAngle

    for k in range(1, nEdges+1, 1):
        right(rotAngle)
        forward(a, color)

# Draws a dummy character (small centered square) with font height h and 
# the colour encoded by colorNo 
def charDummy(h, colorNo) :
    width <- h / 2.0
    # Octagon edge length (here: edge lengzh of the square) 
    b <- width / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- (width - b) / 2.0
    d <- b / math.sqrt(2.0)
    penUp()
    # col69930714 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0-b/2.0)
    right(90)
    forward(c)
    right(90)
    penDown()
    # turtle.pencolor(col69930714)
    # Draws the square with edge length b 
    polygonPart(b, 4, true, 4, colorNo)
    penUp()
    left(90)
    # col7a52f2a2 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b + c)
    left(90)
    backward(h/2.0-b/2.0)
    penDown()
    # turtle.pencolor(col7a52f2a2)

# Draws a comma in colour specified by colorNo with font height h 
# from the current turtle position. 
def comma(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    rotAngle <- math.degrees(math.atan(0.5))
    hypo <- c * math.sqrt(1.25)
    penUp()
    right(90)
    # col4f638935 = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c+b)/2.0 + c)
    penDown()
    # turtle.pencolor(col4f638935)
    # Counterclockwise draw 3 edges of a square with edge length c 
    # in the colour endcoded by colorNo 
    polygonPart(c, 4, true, 3, colorNo)
    left(90)
    forward(c/2.0, colorNo)
    right(90)
    forward(c, colorNo)
    left(180 - rotAngle)
    forward(hypo, colorNo)
    penUp()
    right(90 - rotAngle)
    # col4387b79e = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c + b)/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col4387b79e)

# Draws digit 2 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit2(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    angle <- math.degrees(math.atan(h/(h + 2*c)))
    penUp()
    # col527e5409 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h - c)
    penDown()
    # turtle.pencolor(col527e5409)
    # Clockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 4, colorNo)
    right(angle)
    forward(h/2.0 * math.sqrt(1 + sqr(1+2*c/h)), colorNo)
    left(90 + angle)
    forward(h/2.0, colorNo)
    left(90)

# Draws digit 3 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit3(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # coladd0edd = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(coladd0edd)
    right(180)
    # Counterclockwise draw 6 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 6, colorNo)
    penUp()
    left(180)
    # col2aa3cd93 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b)
    penDown()
    # turtle.pencolor(col2aa3cd93)
    # Counterclockwise draw 5 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 5, colorNo)
    penUp()
    left(45)
    # col7ea37dbf = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h-c)
    left(90)
    forward(h/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col7ea37dbf)

# Draws digit 5 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit5(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # col1d76aeea = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col1d76aeea)
    right(180)
    # Counterclockwise draw 6 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 6, colorNo)
    forward(c, colorNo)
    # Clockwise draw 2 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(h/2.0, 4, false, 2, colorNo)
    penUp()
    left(90)
    # col78dd667e = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col78dd667e)

# Draws digit 6 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit6(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # col78b729e6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col78b729e6)
    right(180)
    # Counterclockwise draw all 8 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 8, colorNo)
    penUp()
    left(180)
    # col6b4a4e18 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b)
    penDown()
    # turtle.pencolor(col6b4a4e18)
    forward(2 * c + b, colorNo)
    # Clockwise draw 3 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 3, colorNo)
    penUp()
    left(135)
    # col27c86f2d = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h-c)
    penDown()
    # turtle.pencolor(col27c86f2d)

# Draws digit 8 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit8(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # col79ad8b2f = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col79ad8b2f)
    right(180)
    # Counterclockwise draw all 8 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 8, colorNo)
    penUp()
    left(180)
    # col1df82230 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b)
    right(45)
    forward(b)
    left(135)
    penDown()
    # turtle.pencolor(col1df82230)
    # Clockwise draw 7 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 7, colorNo)
    penUp()
    left(45)
    # col22635ba0 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    left(90)
    forward(c)
    left(90)
    penDown()
    # turtle.pencolor(col22635ba0)

# Draws digit 9 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit9(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # col5a955565 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col5a955565)
    right(180)
    # Counterclockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(2 * c + b, colorNo)
    # Counterclockwise draw 7 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 7, colorNo)
    penUp()
    left(45)
    # col6293abcc = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h/2.0 + c)
    penDown()
    # turtle.pencolor(col6293abcc)

# Draws an exclamation mark in the colour encoded by colorNo with font height h 
# from the current turtle position. 
def exclMk(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    width <- h/2.0
    length1 <- h - (b+c)/2.0
    length2 <- length1 - 2*c
    hypo <- math.sqrt(width*width/16.0 + length2*length2)
    # 360°/8 
    rotAngle <- 45
    rotAngle2 <- math.degrees(math.atan(width/4.0/length2))
    penUp()
    # col1e730495 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(length1)
    right(90)
    forward(width/2.0)
    left(90 + rotAngle)
    penDown()
    # turtle.pencolor(col1e730495)
    # Clockwise draw 5 edges of an octagon with edge length b/2 
    # in the colour endcoded by colorNo 
    polygonPart(b/2.0, 8, false, 5, colorNo)
    right(rotAngle2)
    forward(hypo, colorNo)
    left(2*rotAngle2)
    forward(-hypo, colorNo)
    penUp()
    # col7d3a22a9 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(hypo)
    right(rotAngle2)
    forward(c)
    left(90)
    forward(c/2.0)
    penDown()
    # turtle.pencolor(col7d3a22a9)
    # Counterclockwise draw all 4 edges of a squarfe with edge length c 
    # in the colour endcoded by colorNo 
    polygonPart(c, 4, false, 4, colorNo)
    penUp()
    # col1d082e88 = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c + b)/2.0)
    left(90)
    backward(c)
    penDown()
    # turtle.pencolor(col1d082e88)

# Draws a full stop in colour specified by colorNo with font height h 
# from the current turtle position. 
def fullSt(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    right(90)
    # col2a32de6c = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c+b)/2.0 + c)
    penDown()
    # turtle.pencolor(col2a32de6c)
    # Counterclockwise draw all 4 edges of a squarfe with edge length c 
    # in the colour endcoded by colorNo 
    polygonPart(c, 4, true, 4, colorNo)
    penUp()
    # col7692d9cc = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c + b)/2.0)
    left(90)
    penDown()
    # turtle.pencolor(col7692d9cc)

# Draws letter Ä in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterAe(h, colorNo) :
    penUp()
    # col75f32542 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    penDown()
    # turtle.pencolor(col75f32542)
    # Clockwise draw all 4 edges of a square with edge length h/16 
    # in the colour endcoded by colorNo 
    polygonPart(max(h/16.0,1), 4, false, 4, colorNo)
    right(90)
    penUp()
    # col7f1302d6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2.0)
    penDown()
    # turtle.pencolor(col7f1302d6)
    # Clockwise draw all 4 edges of a square with edge length h/16 
    # in the colour endcoded by colorNo 
    polygonPart(max(h/16.0,1), 4, false, 4, colorNo)
    right(90)
    penUp()
    # col43ee72e6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    right(90)
    forward(h/2.0)
    penDown()
    # turtle.pencolor(col43ee72e6)
    right(90)
    letterA(h, colorNo)

# Draws letter B in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterB(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    forward(h, colorNo)
    right(90)
    forward(c+b, colorNo)
    # Clockwise draw 4 edges of an octagon with edge length b 
    polygonPart(b, 8, false, 4, colorNo)
    forward(c, colorNo)
    penUp()
    left(180)
    # col2805c96b = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b + c)
    penDown()
    # turtle.pencolor(col2805c96b)
    # Clockwise draw 4 edges of an octagon with edge length b 
    polygonPart(b, 8, false, 4, colorNo)
    forward(c, colorNo)
    penUp()
    left(180)
    # col184cf7cf = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b + 2*c)
    penDown()
    # turtle.pencolor(col184cf7cf)
    left(90)

# Draws letter C in the colour encoded by colorNo with font height h 
# from the current turtle position. 
def letterC(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer triangle at the octagon corner 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col223f3642 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col223f3642)
    right(180)
    # Clockwise draws 3 edges of an octagon with edge length b in the colour 
    # encoded by colorNo 
    polygonPart(b, 8, true, 3, colorNo)
    left(rotAngle)
    penUp()
    # col38c5cc4c = turtle.pencolor(); turtle.pencolor("#000000")
    forward(2*b + 2*c)
    penDown()
    # turtle.pencolor(col38c5cc4c)
    # Counterclockwise draws 4 edges of an octagon with edge length b 
    # iin the colour encoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    penUp()
    # col37918c79 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    left(90)
    # turtle.pencolor(col37918c79)
    forward(b + 2*c, colorNo)
    penDown()
    left(90)

# Draws letter D in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterD(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    forward(h, colorNo)
    right(90)
    forward(c+b, colorNo)
    # Clockwise draw 2 edges of an octagon with edge length b in the colour 
    # encoded by colorNo 
    polygonPart(b, 8, false, 2, colorNo)
    forward(b + 2*c, colorNo)
    # Clockwise draw 2 edges of an octagon with edge length b in the colour 
    # encoded by colorNo 
    polygonPart(b, 8, false, 2, colorNo)
    forward(c, colorNo)
    penUp()
    left(180)
    # col358ee631 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(b + 2*c)
    penDown()
    # turtle.pencolor(col358ee631)
    left(90)

# Draws letter G in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterG(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon. 
    c <- b / math.sqrt(2.0)
    penUp()
    # col60dcc9fe = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col60dcc9fe)
    right(180)
    # Counterclockwise draw 4 edges of an octagon with edge length b in 
    # the colour encoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(c, colorNo)
    left(90)
    forward(b/2.0 + c, colorNo)
    penUp()
    # col222114ba = turtle.pencolor(); turtle.pencolor("#000000")
    backward(b/2.0 + c)
    right(90)
    forward(b + c)
    penDown()
    # turtle.pencolor(col222114ba)
    # Counterclockwise draw 4 edges of an octagon with edge length b in 
    # the colour encoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    penUp()
    # col16e7dcfd = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    left(90)
    # turtle.pencolor(col16e7dcfd)
    forward(b + 2*c, colorNo)
    penDown()
    left(90)

# Draws letter J in colour encoded by colorNo with font height h 
# from the current turtle position. 
def letterJ(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col3901d134 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col3901d134)
    right(180)
    # Counterclockwise draw 3 edges of an octagon with edge length b in 
    # the colour encoded by colorNo 
    polygonPart(b, 8, true, 3, colorNo)
    left(rotAngle)
    forward(h - c, colorNo)
    penUp()
    # col14d3bc22 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col14d3bc22)

# Draws letter O in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterO(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    penUp()
    # col7b227d8d = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col7b227d8d)
    right(180)
    # Counterclockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    # Counterclockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    penUp()
    # col7219ec67 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    left(90)
    forward(b + 2*c)
    penDown()
    # turtle.pencolor(col7219ec67)
    left(90)

# Draws letter P in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterP(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the corner triangle outside the octagon 
    c <- b / math.sqrt(2.0)
    forward(h, colorNo)
    right(90)
    forward(c+b, colorNo)
    # Clockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 4, colorNo)
    forward(c, colorNo)
    penUp()
    # cold706f19 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(b + 2*c)
    left(90)
    forward(b + 2*c)
    penDown()
    # turtle.pencolor(cold706f19)
    left(180)

# Draws letter Q in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterQ(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col27ae2fd0 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col27ae2fd0)
    right(180)
    # Counterclockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    # Counterclockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, true, 4, colorNo)
    forward(b + 2*c, colorNo)
    penUp()
    # col29176cc1 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    left(90)
    forward(b + 2*c)
    # turtle.pencolor(col29176cc1)
    right(rotAngle)
    # col2f177a4b = turtle.pencolor(); turtle.pencolor("#000000")
    backward(b)
    penDown()
    # turtle.pencolor(col2f177a4b)
    forward(b, colorNo)
    left(90 + rotAngle)

# Zeichnet den Buchstaben R von der Turtleposition aus 
# mit Zeilenhöhe h 
def letterR(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    forward(h, colorNo)
    right(90)
    forward(c+b, colorNo)
    # Clockwise draw 4 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 4, colorNo)
    forward(c, colorNo)
    left(90 + rotAngle)
    forward(math.sqrt(2.0)*(b + 2*c), colorNo)
    left(90 + rotAngle)

# Draws letter S in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterS(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Side length of the (outer) corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col1fe20588 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col1fe20588)
    right(180)
    # Counterclockwise draw 6 edges of an octagon with edge length b 
    # in the colour encoded by colorNo 
    polygonPart(b, 8, true, 6, colorNo)
    # Clockwise draw 5 edges of an octagon with edge length b 
    # in the colour encoded by colorNo 
    polygonPart(b, 8, false, 5, colorNo)
    right(rotAngle)
    penUp()
    # col6ce139a4 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(2*b + 3*c)
    penDown()
    # turtle.pencolor(col6ce139a4)
    left(180)

# Draws letter U in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterU(h, colorNo) :
    # edge length of a regular octagon 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col47542153 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    penDown()
    # turtle.pencolor(col47542153)
    forward(h - c, colorNo)
    penUp()
    # col33afa13b = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h-c)
    penDown()
    # turtle.pencolor(col33afa13b)
    right(180)
    # Counterclockwise draw 3 edges of an octagoin with edge length b in colour specified by colorNo 
    polygonPart(b, 8, true, 3, colorNo)
    left(rotAngle)
    forward(h - c, colorNo)
    penUp()
    # col7a4ccb53 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(h)
    penDown()
    # turtle.pencolor(col7a4ccb53)

# Draws a question mark in colour specified by colorNo with font height h 
# from the current turtle position. 
def qstnMk(h, colorNo) :
    # Octagon edge length 
    b <- h * 0.5 / (math.sqrt(2.0) + 1)
    # Cathetus of the outer corner triangle of the octagon 
    c <- b / math.sqrt(2.0)
    # 360°/8 
    rotAngle <- 45
    penUp()
    # col4445629 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h-c)
    penDown()
    # turtle.pencolor(col4445629)
    # Counterclockwise draw 5 edges of an octagon with edge length b 
    # in the colour endcoded by colorNo 
    polygonPart(b, 8, false, 5, colorNo)
    forward(c, colorNo)
    left(rotAngle)
    forward(b/2.0, colorNo)
    penUp()
    # col45b9a632 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(c)
    left(90)
    forward(c/2.0)
    penDown()
    # turtle.pencolor(col45b9a632)
    # Counterclockwise draw all 4 edges of a squarfe with edge length c 
    # in the colour endcoded by colorNo 
    polygonPart(c, 4, false, 4, colorNo)
    penUp()
    # col25d250c6 = turtle.pencolor(); turtle.pencolor("#000000")
    forward((c + b)/2.0)
    left(90)
    backward(c)
    penDown()
    # turtle.pencolor(col25d250c6)

# Draws digit 0 in the colour specified by colorNo with font height h 
# from the current turtle position. 
def digit0(h, colorNo) :
    penUp()
    # col6b26e945 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/4.0)
    penDown()
    # turtle.pencolor(col6b26e945)
    right(45)
    len <- h/math.sqrt(2)
    forward(len, colorNo)
    penUp()
    # col63a65a25 = turtle.pencolor(); turtle.pencolor("#000000")
    backward(len)
    left(45)
    backward(h/4.0)
    # turtle.pencolor(col63a65a25)
    letterO(h, colorNo)

# Draws letter Ö in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterOe(h, colorNo) :
    penUp()
    # col54c562f7 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    penDown()
    # turtle.pencolor(col54c562f7)
    right(90)
    # Clockwise draw all 4 edges of a square with edge length h/8 
    # in the colour endcoded by colorNo 
    polygonPart(h/8, 4, false, 4, colorNo)
    penUp()
    # col318ba8c8 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2)
    penDown()
    # turtle.pencolor(col318ba8c8)
    right(90)
    # Clockwise draw all 4 edges of a square with edge length h/8 
    # in the colour endcoded by colorNo 
    polygonPart(h/8, 4, false, 4, colorNo)
    penUp()
    # col6dbb137d = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    penDown()
    # turtle.pencolor(col6dbb137d)
    right(90)
    penUp()
    # col3c9d0b9d = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2)
    penDown()
    # turtle.pencolor(col3c9d0b9d)
    right(90)
    letterO(h, colorNo)

# Draws letter Ü in colour specified by colorNo with font height h 
# from the current turtle position. 
def letterUe(h, colorNo) :
    penUp()
    # col43301423 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    right(90)
    forward(max(h/8,1))
    penDown()
    # turtle.pencolor(col43301423)
    # Clockwise draw all 4 edges of a square with edge length h/16 
    # in the colour endcoded by colorNo 
    polygonPart(max(h/16,1), 4, false, 4, colorNo)
    penUp()
    # col2f112965 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h/2 - 2 * max(h/8,1) - max(h/16, 1))
    penDown()
    # turtle.pencolor(col2f112965)
    # Clockwise draw all 4 edges of a square with edge length h/16 
    # in the colour endcoded by colorNo 
    polygonPart(max(h/16,1), 4, false, 4, colorNo)
    penUp()
    # col1a04f701 = turtle.pencolor(); turtle.pencolor("#000000")
    forward(max(h/8,1))
    penDown()
    # turtle.pencolor(col1a04f701)
    right(90)
    penUp()
    # col4e91d63f = turtle.pencolor(); turtle.pencolor("#000000")
    forward(h)
    right(90)
    forward(h/2)
    penDown()
    # turtle.pencolor(col4e91d63f)
    right(90)
    letterU(h, colorNo)

# Has the turtle draw the given string 'text´ with font height 'h´ (in 
# pixels) and the colour coded by integer 'c´ from the current Turtle 
# position to the Turtle canvas. If the turtle looks North then 
# the text will be written rightwards. In the event, the turtle will be 
# placed behind the text in original orientation (such that the next text 
# would be written like a continuation. Colour codes: 
# 1 = black 
# 2 = red 
# 3 = yellow 
# 4 = green 
# 5 = cyan 
# 6 = blue 
# 7 = pink 
# 8 = grey 
# 9 = orange 
# 10 = violet 
# All letters (ASCII) will be converted to uppercase, 
# the set of representable special characters is: decimal digits, 
# '.', ',', '!', '?', 'Ä', 'Ö', 'Ü'. Other characters will be shown as a small 
# centred square (dummy character). 
def drawText(text, h, c) :
    gap <- h/10.0
    for k in range(1, length(text)+1, 1):
        letter <- uppercase(copy(text, k, 1))
        if ((letter) == "A") :
            letterA(h,c)
        elif ((letter) == "B") :
            letterB(h,c)
        elif ((letter) == "C") :
            letterC(h,c)
        elif ((letter) == "D") :
            letterD(h,c)
        elif ((letter) == "E") :
            letterE(h,c)
        elif ((letter) == "F") :
            letterF(h,c)
        elif ((letter) == "G") :
            letterG(h,c)
        elif ((letter) == "H") :
            letterH(h,c)
        elif ((letter) == "I") :
            letterI(h,c)
        elif ((letter) == "J") :
            letterJ(h,c)
        elif ((letter) == "K") :
            letterK(h,c)
        elif ((letter) == "L") :
            letterL(h,c)
        elif ((letter) == "M") :
            letterM(h,c)
        elif ((letter) == "N") :
            letterN(h,c)
        elif ((letter) == "O") :
            letterO(h,c)
        elif ((letter) == "P") :
            letterP(h,c)
        elif ((letter) == "Q") :
            letterQ(h,c)
        elif ((letter) == "R") :
            letterR(h,c)
        elif ((letter) == "S") :
            letterS(h,c)
        elif ((letter) == "T") :
            letterT(h,c)
        elif ((letter) == "U") :
            letterU(h,c)
        elif ((letter) == "V") :
            letterV(h,c)
        elif ((letter) == "W") :
            letterW(h,c)
        elif ((letter) == "X") :
            letterX(h,c)
        elif ((letter) == "Y") :
            letterY(h,c)
        elif ((letter) == "Z") :
            letterZ(h,c)
        elif ((letter) == " ") :
            blank(h,c)
        elif ((letter) == "!") :
            exclMk(h,c)
        elif ((letter) == "?") :
            qstnMk(h,c)
        elif ((letter) == ".") :
            fullSt(h,c)
        elif ((letter) == ",") :
            comma(h,c)
        elif ((letter) == "Ä") :
            letterAe(h,c)
        elif ((letter) == "Ö") :
            letterOe(h,c)
        elif ((letter) == "Ü") :
            letterUe(h,c)
        elif ((letter) == "0") :
            digit0(h,c)
        elif ((letter) == "1") :
            digit1(h,c)
        elif ((letter) == "2") :
            digit2(h,c)
        elif ((letter) == "3") :
            digit3(h,c)
        elif ((letter) == "4") :
            digit4(h,c)
        elif ((letter) == "5") :
            digit5(h,c)
        elif ((letter) == "6") :
            digit6(h,c)
        elif ((letter) == "7") :
            digit7(h,c)
        elif ((letter) == "8") :
            digit8(h,c)
        elif ((letter) == "9") :
            digit9(h,c)
        else:
            charDummy(h,c)

        right(90)
        penUp()
        # col419c5f1a = turtle.pencolor(); turtle.pencolor("#000000")
        forward(gap)
        penDown()
        left(90)
        # turtle.pencolor(col419c5f1a)

# = = = = 8< = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

# Demo program for routine drawText() 
# Asks the user to enter a text, a wanted text height and colour, 
# and then draws this string onto the turtle screen. Places every 
# entered text to a new line. 
print("This is a demo program for text writing with Turleizer.", sep='')
showTurtle()
penDown()
y <- 0
while True:
    text = input("Enter some text (empty string to exit)")
    # Make sure the content is interpreted as string 
    text <- "" + text
    if (text <> ""):
        while True:
            height = input("Height of the text (pixels)")
            if height >= 5:
                break

        while True:
            colour = input("Colour (1=black, 2=red, 3=yellow, 4=green, 5=cyan, 6=blue, 7=pink, 8=gray, 9=orange, 10=violet)")
            if colour >= 1 and colour <= 10:
                break

        y <- y + height + 2
        gotoXY(0, y - 2)
        drawText(text, height, colour)

    if text = "":
        break

gotoXY(0, y + 15)
drawText("Thank you, bye.", 10, 4)
hideTurtle()

